Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG: # только если DEBUG=True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'  # для href="{% url 'blog:detail' post.id %}"

urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>', views.detail, name='detail'),  # <int:blog_id> автоматически принимает значения

]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_time = models.DateTimeField()

    def __str__(self):  # Позволяет показывать названия проектов в админке
        return self.title  # можно также добавить описание

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)  # blank=True - позволяет открывать ссылку в новой вкладке

    def __str__(self):  # Позволяет показывать названия проектов в админке
        return self.title  # можно также добавить описание

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def all_blog(request):
    posts = Post.objects.order_by('-date_time') # order_by('-date_time'), где date_time это поле таблицы. упорядочивает посты по дате
    return render(request, 'blog/all_blog.html', {'posts': posts})


def detail(request, blog_id):
    post = get_object_or_404(Post, pk=blog_id)  # kp - Primary Key - для обращение к базе данных по первичному ключу
    return render(request, 'blog/detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project



def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blog.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">SHIBZUKO {{ blogs.count }} {{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}



    {% load static %}

    <h1>{{ post.title }}</h1>
    <h2>{{ post.date_time }}</h2>
    <h2>{{ post.description|safe }}</h2>




{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'portfolio/logo.png' %}">

  <title>shibzuko</title>
</head>

<body>
  {% load static %}
  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/logo.png' %}" width="70" height="40" class="d-inline-block align-top" alt="Shibzuko Logo">
        <span>Shibzuko</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/shibzuko" target="_blank">Github</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/azamat-shibzukhov-03b09b26a/" target="_blank">Linkedin</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}



<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/photo_1.webp' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Джун-стажун в поисках оффера 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}